/*
 * Jim static extensions.  Based on the autogenerated file.
 */

#include "jim.h"
#include "jimautoconf.h"

int Jim_InitStaticExtensions(Jim_Interp *interp)
{
	extern int Jim_arrayInit(Jim_Interp *);
	extern int Jim_namespaceInit(Jim_Interp *);

	Jim_arrayInit(interp);
	Jim_namespaceInit(interp);
	return JIM_OK;
}
